apiVersion: v2
name: harbor-container-webhook
description: Webhook to configure pods with harbor proxy cache projects
type: application
version: 0.4.1
appVersion: "0.4.1"
kubeVersion: ">= 1.16.0-0"
home: https://github.com/IndeedEng-alpha/harbor-container-webhook
maintainers:
  - name: cnmcavoy
    email: cmcavoy@indeed.com
